import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

// This defines the banner at the top of the generated outfile, e.g. main.js
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	bundle: true,
	entryPoints: ["src/main.ts"],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	jsxFactory: "h",
	jsxFragment: "Fragment",
	target: "es2018",
	loader: {
		".ts": "ts",
		".tsx": "tsx",
	},
	logLevel: "info",
	outfile: "main.js",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
